# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure languages of the site.

[es]
  languageCode = "es-es"
  languageName = "Castellano"
  contentDir = "content/es"

[eu]
  languageCode = "es-eu"
  languageName = "Euskara"
  # contentDir = "content/eu"

# Uncomment the lines below to configure your website in a second language.
#[en]
#  languageCode = "en-us"
#  contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
#[zh]
#  languageCode = "zh-Hans"
#  contentDir = "content/zh"
#  title = "Chinese website title..."
#  [zh.params]
#    description = "Site description in Chinese..."
#  [[zh.menu.main]]
#    name = "Wo"
#    url = "#about"
#    weight = 1
